-- all_tables: 테이블명 → PK 컬럼명 매핑 (복합키는 테이블당 여러 행 → PK 제약 없음)
SET NAMES utf8mb4;
USE nogada;

CREATE TABLE all_tables (
  table_id   VARCHAR(30) NOT NULL,
  pk_column  VARCHAR(30) NOT NULL
);

INSERT INTO all_tables (table_id, pk_column) VALUES
  ('PFO_STCK_MA', 'mncm_code'),
  ('PFO_STCK_MA', 'fund_code'),
  ('PFO_STCK_MA', 'proc_date'),
  ('PFO_STCK_MA', 'itms_code'),
  ('PFO_BRWN_STCK_MA', 'mncm_code'),
  ('PFO_BRWN_STCK_MA', 'fund_code'),
  ('PFO_BRWN_STCK_MA', 'proc_date'),
  ('PFO_BRWN_STCK_MA', 'itms_code'),
  ('PFO_SPA_MA', 'mncm_code'),
  ('PFO_SPA_MA', 'fund_code'),
  ('PFO_SPA_MA', 'proc_date'),
  ('PFO_SPA_MA', 'itms_code'),
  ('PFO_BOND_INTG_MA', 'mncm_code'),
  ('PFO_BOND_INTG_MA', 'fund_code'),
  ('PFO_BOND_INTG_MA', 'proc_date'),
  ('PFO_BOND_INTG_MA', 'itms_code'),
  ('PFO_CLFD_MIP_MA', 'mncm_code'),
  ('PFO_CLFD_MIP_MA', 'fund_code'),
  ('PFO_CLFD_MIP_MA', 'proc_date'),
  ('PFO_CLFD_REVS_STPR_MA', 'mncm_code'),
  ('PFO_CLFD_REVS_STPR_MA', 'fund_code'),
  ('PFO_CLFD_REVS_STPR_MA', 'proc_date'),
  ('PFO_CLFD_PRDT_MIP_MA', 'mncm_code'),
  ('PFO_CLFD_PRDT_MIP_MA', 'fund_code'),
  ('PFO_CLFD_PRDT_MIP_MA', 'proc_date'),
  ('PFO_EAR_TR', 'mncm_code'),
  ('PFO_EAR_TR', 'fund_code'),
  ('PFO_EAR_TR', 'proc_date'),
  ('PFO_EAR_TR', 'itms_code'),
  ('PFO_EAR_TR', 'ordernum'),
  ('PFO_STCK_TR', 'mncm_code'),
  ('PFO_STCK_TR', 'fund_code'),
  ('PFO_STCK_TR', 'proc_date'),
  ('PFO_STCK_TR', 'itms_code'),
  ('PFO_STCK_TR', 'ordernum'),
  ('PFO_TAMI_SM', 'mncm_code'),
  ('PFO_TAMI_SM', 'fund_code'),
  ('PFO_TAMI_SM', 'proc_date'),
  ('PFO_CLPR_RECV_SM', 'rcms_finm'),
  ('PFO_CLPR_RECV_SM', 'proc_date'),
  ('PFO_CLPR_RECV_SM', 'seq'),
  ('PFO_FUND_HT', 'mncm_code'),
  ('PFO_FUND_HT', 'fund_code'),
  ('PFO_FUND_HT', 'proc_date'),
  ('PFO_FUND_INFR_HT', 'mncm_code'),
  ('PFO_FUND_INFR_HT', 'fund_code'),
  ('PFO_FUND_INFR_HT', 'proc_date'),
  ('TRU_STCK_ITMS_HT', 'proc_date'),
  ('TRU_STCK_ITMS_HT', 'itms_code'),
  ('PFO_SPA_ITMS_HT', 'proc_date'),
  ('PFO_SPA_ITMS_HT', 'itms_code'),
  ('PFO_FUND_BS', 'mncm_code'),
  ('PFO_FUND_BS', 'fund_code'),
  ('TRU_MNCM_BS', 'mncm_code'),
  ('TRU_TRPL_BS', 'trpl_code'),
  ('PFO_MNCM_CLCD_HT', 'mncm_code'),
  ('PFO_MNCM_CLCD_HT', 'mncm_gpcd'),
  ('PFO_MNCM_CLCD_HT', 'dtl_code'),
  ('PFO_MNCM_CLCD_HT', 'seq'),
  ('PFO_DATE_MNGM_BS', 'prsn_date'),
  ('PFO_BM_STUP_TEMPLT_BS', 'mncm_code'),
  ('PFO_BM_STUP_TEMPLT_BS', 'bm_templt_code'),
  ('PFO_CLFD_BM_TEMPLT_HT', 'mncm_code'),
  ('PFO_CLFD_BM_TEMPLT_HT', 'bm_templt_code'),
  ('PFO_CLFD_BM_TEMPLT_HT', 'strn_date'),
  ('PFO_FUND_OVRV_PDAY_BS', 'mncm_code'),
  ('PFO_FUND_OVRV_PDAY_BS', 'aply_date'),
  ('PFO_FUND_OVRV_PDAY_BS', 'rprt_fund_code'),
  ('PFO_FUND_OVRV_PDAY_BS', 'dtl_code'),
  ('RPT_RLGR_TM', 'btch_uniq_id'),
  ('TRU_CMN_SRCH_SLCT_TM', 'code_slct_code'),
  ('TRU_CMN_SRCH_SLCT_TM', 'clmn_id'),
  ('TRU_CMN_SRCH_SLCT_TM', 'dtl_code'),
  ('TRU_SRVC_BTN_LB', 'mncm_code'),
  ('TRU_SRVC_BTN_LB', 'proc_date'),
  ('TRU_SRVC_BTN_LB', 'srvc_code'),
  ('TRU_SRVC_BTN_LB', 'seq');
